Assets/Scenes/WallFollowerExperiment.unity
Assets/Scenes/WallFollowerExperiment.unity.meta
Assets/Scripts/ExplorationAlgorithm/WallFollower.meta
Assets/Scripts/ExplorationAlgorithm/WallFollower/WallFollower.cs
Assets/Scripts/ExplorationAlgorithm/WallFollower/WallFollower.cs.meta
Assets/Scripts/Map/RayTracingMap.cs
Assets/Scripts/WallFollowerExperiment.cs
Assets/Scripts/WallFollowerExperiment.cs.meta

This algorithm is grid based so a lot of effort has been made to make it work.
The raycast thingamagic crashes on triangle intersect for some reason sometimes this is not our code that does this.

Wall follower Algorithm

---

.gitignore
Assets/EditTests/EditTests.asmdef
Assets/PlayModeTests/PlayModeTests.asmdef
Assets/ROS-TCP-Connector/com.unity.robotics.ros-tcp-connector/Editor/Unity.Robotics.ROSTCPConnector.Editor.asmdef
Assets/ROS-TCP-Connector/com.unity.robotics.ros-tcp-connector/Tests/Editor/Unity.Robotics.ROSTCPConnector.Editor.Tests.asmdef
Assets/Scripts/CustomScriptsAssembly.asmdef
Assets/Scripts/ExampleProgramOneRobotAndSimulation.cs
Assets/Scripts/ExampleProgramOneRobotAndSimulation.cs.meta
Assets/Scripts/ExplorationAlgorithm/FollowWaypoints.meta
Assets/Scripts/ExplorationAlgorithm/FollowWaypoints/FollowWaypointsAlgorithm.cs
Assets/Scripts/ExplorationAlgorithm/FollowWaypoints/FollowWaypointsAlgorithm.cs.meta
Assets/Scripts/Map/CoarseGrainedMap.cs
Assets/Scripts/Map/SlamMap.cs

Add the functionality for robot to know the map in advance.
By default, the map is not known and need to be set manually to true in the code, so need to further add code/support for define whether know the map in advance or not.

Able to knowing the map in advance

---

Assets/Scripts/ExplorationAlgorithm/HenrikAlgo.meta
Assets/Scripts/ExplorationAlgorithm/HenrikAlgo/HenrikExplorationAlgorithm.cs
Assets/Scripts/ExplorationAlgorithm/HenrikAlgo/HenrikExplorationAlgorithm.cs.meta
Assets/Scripts/HenrikExample.cs
Assets/Scripts/HenrikExample.cs.meta
Assets/Scripts/Robot/IRobotController.cs
Assets/idk.unity
Assets/idk.unity.meta
Packages/manifest.json
Packages/packages-lock.json

Adds a slightly janky breath first search exploration algorithm.
I continuously moves to the nearest unseen tile.
The jankyness stems from it colliding with walls, but to fix it, it reversed 0.5 meters and tries again until it is successful.
280 lines of c#
Coauthored by: @miniJmo

Breath first search exploration

---

Assets/Scripts/UI/Patrolling.meta
Assets/Scripts/UI/Patrolling/ProgressBar.prefab
Assets/Scripts/UI/Patrolling/ProgressBar.prefab.meta
Assets/Scripts/UI/Patrolling/Stats.cs.meta
Assets/Scripts/UI/Patrolling/StoppingCriteria.cs
Assets/Scripts/UI/Patrolling/StoppingCriteria.cs.meta

Added the progressbar as a asset for later use when patrolling UI is developed

Added progressbar script

---

Assets/Scripts/Map/Vertex.cs
Assets/Scripts/PatrollingAlgorithm/ConscientiousReactiveAlgorithm.cs

This PR changes the definition of Vertex class, such that it only captures the latest tick it was visited.
Codes that gives errors are commented out and will be fixed in the next PR

1. Change the vertex class

---

Assets/Scripts/PatrollingAlgorithm/ConscientiousReactiveAlgorithm.cs
Assets/Scripts/Robot/MonaRobot.cs
Assets/Scripts/Robot/Robot2DController.cs

Able to get the current tick from the simulation and changed the CR algorithm to adapt that

2. Get the current tick from the simulation to the patrolling algorithm

---

Assets/Scripts/ExperimentSimulations/ConscientiousReactiveExperiment.cs
Assets/Scripts/Simulation/PatrollingSimulation.cs
Assets/Scripts/Trackers/PatrollingTracker.cs
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs

Still missing the setup UI for patrolling

Initial setup for patrolling

---

Assets/Scripts/UI/Patrolling/Visualization Options.prefab
Assets/Scripts/UI/Patrolling/Visualization Options.prefab.meta

This is only the prefab, the functionality of the buttons is still missing

The UI for visualization options

---

Packages/packages-lock.json
ProjectSettings/ProjectVersion.txt

Everyone will use this version.
Closes #52

Specify unity-version to use

---

Assets/Scripts/Trackers/PatrollingTracker.cs

Able to get the completed cycles and average graph difference between last two cycles in proportion unit

Able to get the CompletedCycles and AverageGraphDiffLastTwoCyclesProportion

---

Assets/Scripts/UI/Patrolling/Patrolling UI.prefab
Assets/Scripts/UI/Patrolling/Patrolling UI.prefab.meta

Needs to add functionality to the u
It looks like this:

Entire UI created

---

.github/workflows/main.yml

Add formatting to ci

---

Assets/Scripts/GlobalSettings.cs
Assets/Scripts/Map/Vertex.cs
Assets/Scripts/Map/Visualization/WaypointHeatMapVisualization.cs
Assets/Scripts/Map/Visualization/WaypointHeatMapVisualization.cs.meta
Assets/Scripts/Statistics/PatrollingVisualizer.cs
Assets/Scripts/Trackers/PatrollingTracker.cs
Assets/Scripts/Trackers/Tracker.cs
Assets/Scripts/Trackers/VertexDetails.cs
Assets/Scripts/UI/Patrolling.meta
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs

A picture of how it looks in the simulator:

UI waypoint heatmap

---

Assets/PlayModeTests/CommunicationTest.cs
Assets/PlayModeTests/MaterialCommunicationTest.cs
Assets/PlayModeTests/MinotaurDoorwayTest.cs
Assets/PlayModeTests/Robot2DControllerTest.cs
Assets/Resources/ROSConnectionPrefab.prefab
Assets/Scripts/ExperimentSimulations/AvariceExperiment.cs
Assets/Scripts/ExperimentSimulations/AvariceExploratoryExperiment.cs
Assets/Scripts/ExperimentSimulations/ConscientiousReactiveExperiment.cs
Assets/Scripts/ExperimentSimulations/ExampleProgram.cs
Assets/Scripts/ExperimentSimulations/ExampleProgramOneRobotAndSimulation.cs
Assets/Scripts/ExperimentSimulations/ExplorationExperimentBase.cs
Assets/Scripts/ExperimentSimulations/ExplorationTimeoutTest.cs
Assets/Scripts/ExperimentSimulations/HenrikExample.cs
Assets/Scripts/ExperimentSimulations/MinotaurExperiments.cs
Assets/Scripts/ExperimentSimulations/TnfExperiments.cs
Assets/Scripts/ExperimentSimulations/WallFollowerExperiment.cs
Assets/Scripts/ExplorationAlgorithm/Minotaur/Doorway.cs
Assets/Scripts/ExplorationAlgorithm/Minotaur/MinotaurAlgorithm.cs
Assets/Scripts/Map/MapGen/BuildingGenerator.cs
Assets/Scripts/Map/MapGen/MapGenerator.cs
Assets/Scripts/Map/RobotSpawners/RobotSpawner.cs
Assets/Scripts/Simulation/ExplorationSimulator.cs
Assets/Scripts/Simulation/PatrollingSimulator.cs
Assets/Scripts/Simulation/SimulationManager.cs
Assets/Scripts/Simulation/Simulator.cs
Assets/Scripts/UI/SimulationSpeedController.cs
Assets/Scripts/UI/Tooltip.cs

Reduce the amount of singletons and finding gameobjects.
Depends on #77

Remove static and GameObject.Find where feasible

---

Assets/Prefabs/Patrolling/PatrollingVisualizer.prefab
Assets/Scripts/Statistics/ExplorationVisualizer.cs
Assets/Scripts/Statistics/PatrollingVisualizer.cs
Assets/Scripts/Statistics/Visualizer.cs
Assets/Scripts/Statistics/Visualizer.cs.meta

A abstract visualizer since the exploration visualizer had some functionality that also will be used in the patrolling visualizer, when show the heat map.

1. Abstract Visualizer

---

Assets/Scripts/Statistics/ExplorationTracker.cs
Assets/Scripts/Trackers/Tracker.cs

This PR enables the coverage calculator update for patrolling tracker since it was only applied for the exploration before

2. applying the coverage calculator for the patrolling tracker

---

Assets/Scripts/ExperimentSimulations/ConscientiousReactiveExperiment.cs
Assets/Scripts/ExperimentSimulations/RandomReactiveExperiment.cs
Assets/Scripts/Simulation/ExplorationSimulation.cs
Assets/Scripts/Simulation/PatrollingSimulation.cs
Assets/Scripts/Simulation/SimulationScenarios/PatrollingSimulationScenario.cs
Assets/Scripts/Simulation/SimulationScenarios/SimulationScenario.cs
Assets/Scripts/Trackers/PatrollingTracker.cs
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs

Added stopping criteria to patrolling

Added stopping criteria to patrolling

---

Assets/Scripts/Trackers/PatrollingTracker.cs
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs

This PR connectsTargetWaypointSelectedButton and VisibleSelectedButton to UI, but without any actions to the button, which will be set up later.

Connecting TargetWaypointSelectedButton and VisibleSelectedButton to UI

---

Assets/Scripts/Map/MapPatrollingGen/PatrollingMapSpawner.cs
Assets/Scripts/Map/MapPatrollingGen/PatrollingWaypointGenerator.cs
Assets/Scripts/Map/MapPatrollingGen/PatrollingWaypointGenerator.cs.meta
Assets/Scripts/Map/PatrollingMap.cs
Assets/Scripts/Statistics/PatrollingVisualizer.cs
Assets/package.json
Packages/manifest.json
Packages/packages-lock.json

Missing adding neighboring points as neighbors

Delaunay triangulation method for waypoints

---

Assets/Scripts/ExplorationAlgorithm/Minotaur/Messages/AuctionResultMessage.cs
Assets/Scripts/ExplorationAlgorithm/Minotaur/Messages/BiddingMessage.cs
Assets/Scripts/ExplorationAlgorithm/Minotaur/Messages/DoorwayFoundMessage.cs
Assets/Scripts/ExplorationAlgorithm/Minotaur/MinotaurAlgorithm.cs
Assets/Scripts/ExplorationAlgorithm/SSB/SSBAlgorithm.cs
Assets/Scripts/ExplorationAlgorithm/TheNextFrontier/TnfExplorationAlgorithm.cs
Assets/Scripts/ExplorationAlgorithm/TheNextFrontier/ffTnfExplorationAlgorithm.cs
Assets/Scripts/Map/CoarseGrainedMap.cs
Assets/Scripts/Map/PathFinding/AStar.cs
Assets/Scripts/Map/PathFinding/PathStep.cs
Assets/Scripts/Map/RayTracingMap.cs
Assets/Scripts/Map/SimulationMap.cs
Assets/Scripts/Map/SlamMap.cs
Assets/Scripts/Map/Visualization/Exploration/AllRobotsCoverageVisualization.cs
Assets/Scripts/Map/Visualization/Exploration/AllRobotsExplorationVisualization.cs
Assets/Scripts/Map/Visualization/Exploration/CoverageHeatMapVisualization.cs
Assets/Scripts/Map/Visualization/Exploration/CurrentlyVisibleAreaVisualizationExploration.cs
Assets/Scripts/Map/Visualization/Exploration/ExplorationHeatMapVisualization.cs
Assets/Scripts/Map/Visualization/Exploration/IExplorationVisualizationMode.cs
Assets/Scripts/Map/Visualization/Exploration/SelectedRobotSlamMapVisualization.cs
Assets/Scripts/Simulation/SimulationManager.cs
Assets/Scripts/Utilities/CardinalDirection.cs
Assets/Scripts/Utilities/Functional.cs
Assets/Scripts/Utilities/Line2D.cs

Inline stuff
Make stuff structs
Only do visible triangles if requested

Optimize stuff 2

---

Assets/Scripts/Trackers/PatrollingTracker.cs
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs

- Added auto scaling/zoom to the graph
- Made it only plot when the graph is active
- The graph is less likely to crash due to vertex limitations now.

Improved idleness graph

---

Assets/Scripts/Map/MapPatrollingGen/PatrollingMapRectangleGen.cs

Optimize rectangle gen

---

Assets/PlayModeTests/Robot2DControllerTest.cs
Assets/Scripts/Robot/IRobotController.cs
Assets/Scripts/Robot/Robot2DController.cs

Added:
- EstimateTimeToTarget
- EstimateDistanceToTarget

Add estimation methods to RobotController

---

Assets/Scripts/Map/MapPatrollingGen/PatrollingWaypointGenerator.cs

https://github.com/nol1fe/delaunator-sharp/tree/master

Ref to the nuget package delaunator 

---

Assets/Scripts/Map/MapPatrollingGen/WatchmanRouteSolver.cs

Added in the watchman route solver that waypoints cant be placed close to walls. This change removes the possiblity to place waypoints in doors and close to walls

Updated waypoint generation

---

Assets/PlayModeTests/EstimateTickTest.meta
Assets/PlayModeTests/EstimateTickTest/EstimateTestStraightPath.cs
Assets/PlayModeTests/EstimateTickTest/EstimateTestStraightPath.cs.meta
Assets/PlayModeTests/EstimateTickTest/EstimateTestTurnsPath.cs
Assets/PlayModeTests/EstimateTickTest/EstimateTestTurnsPath.cs.meta
Assets/PlayModeTests/EstimateTickTest/TestToTargetTileAlgorithm.cs
Assets/PlayModeTests/EstimateTickTest/TestToTargetTileAlgorithm.cs.meta
Assets/Scripts/Simulation/SimulationBase.cs
Assets/Scripts/Utilities/EstimateTickTimeCalculator.cs
Assets/Scripts/Utilities/EstimateTickTimeCalculator.cs.meta

A another way of calculating the estimate ticks it takes to from start to end by simulating. Instead of make a new simulation, I have selected the specific part that are relevant for estimating.

Estimate with taking rotation into account

---

Assets/Prefabs/UI.meta
Assets/Prefabs/UI/CompletedCycleProgressBar.prefab
Assets/Prefabs/UI/CompletedCycleProgressBar.prefab.meta
Assets/Prefabs/UI/ControlPanel.prefab
Assets/Prefabs/UI/ControlPanel.prefab.meta
Assets/Prefabs/UI/CoordinateDisplay.prefab
Assets/Prefabs/UI/CoordinateDisplay.prefab.meta
Assets/Prefabs/UI/DebugInfoContainer.prefab
Assets/Prefabs/UI/DebugInfoContainer.prefab.meta
Assets/Prefabs/UI/GraphUI.prefab
Assets/Prefabs/UI/GraphUI.prefab.meta
Assets/Prefabs/UI/RestartAndRemakePanel.prefab
Assets/Prefabs/UI/RestartAndRemakePanel.prefab.meta
Assets/Prefabs/UI/SettingsPanel.prefab
Assets/Prefabs/UI/SettingsPanel.prefab.meta
Assets/Prefabs/UI/Stats.prefab
Assets/Prefabs/UI/Stats.prefab.meta
Assets/Prefabs/UI/StatusText.prefab
Assets/Prefabs/UI/StatusText.prefab.meta
Assets/Prefabs/UI/StoppingCriteriaContainer.prefab
Assets/Prefabs/UI/StoppingCriteriaContainer.prefab.meta
Assets/Prefabs/UI/VersionNumber.prefab
Assets/Prefabs/UI/VersionNumber.prefab.meta
Assets/Prefabs/UI/ViewControlPanel.prefab
Assets/Prefabs/UI/ViewControlPanel.prefab.meta
Assets/Prefabs/UI/VisualiztionOptions.prefab
Assets/Prefabs/UI/VisualiztionOptions.prefab.meta
Assets/Scripts/Simulation/SimulationManager.cs
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs

Also improved scaling of some elements, the graph can still be improved in terms of scaling.

Split up the prefab

---

Assets/Scripts/ExperimentSimulations/ConscientiousReactiveExperiment.cs
Assets/Scripts/ExplorationAlgorithm/Greed/Greed.cs
Assets/Scripts/ExplorationAlgorithm/Minotaur/Messages/DoorwayFoundMessage.cs
Assets/Scripts/ExplorationAlgorithm/Minotaur/MinotaurAlgorithm.cs
Assets/Scripts/Map/CoarseGrainedMap.cs
Assets/Scripts/Map/PathFinding/AStar.cs
Assets/Scripts/Map/SlamMap.cs
Assets/Scripts/PatrollingAlgorithms/PatrollingAlgorithm.cs
Assets/Scripts/Robot/IRobotController.cs
Assets/Scripts/Robot/Robot2DController.cs
Assets/Scripts/Simulation/PatrollingSimulation.cs
Assets/Scripts/Simulation/SimulationBase.cs

Updated CR experiment
Fixed pathing trough walls
Fixed robot alignment

Fixing bugs

---

Assets/Scripts/Map/MapPatrollingGen/WatchmanRouteSolver.cs

The problem this was mitigating has been fixed

Remove IsCloseToWall in WatchmanRouteSolver

---

Assets/PlayModeTests/EstimateTickTest/EstimateTestStraightPath.cs
Assets/PlayModeTests/EstimateTickTest/EstimateTestTurnsPath.cs
Assets/Scripts/Utilities/EstimateTickTimeCalculator.cs

This PR fixes the tests for estimate

Fix estimate test

---

Assets/PlayModeTests/Robot2DControllerTest.cs
Assets/Scripts/Robot/Robot2DController.cs
Assets/Scripts/Trackers/PatrollingTracker.cs

The total traveled distance for a robot is calculate every logic update where the distance between the previous and the current location is calculated and then accumulated over each logic tick.

Calculating the total traveled distance ✅

---

.gitignore
Assets/Resources/Patrolling_MAEPS.prefab
Assets/Scripts/Simulation/PatrollingSimulation.cs

Made graph invisible by default.
Added functionality to save the chart along with the csv data
Added Data to the gitignore.

Save chart

---

Assets/EditTests/ComputeVisibilityTest.cs
Assets/Prefabs/UI/SettingsPanel.prefab
Assets/Prefabs/UI/VisualiztionOptions.prefab
Assets/Scripts/Map/MapPatrollingGen/WatchmanRouteSolver.cs
Assets/Scripts/Map/Visualization/Patrolling/LineOfSightAllVerticesVisualizationMode.cs
Assets/Scripts/Map/Visualization/Patrolling/LineOfSightAllVerticesVisualizationMode.cs.meta
Assets/Scripts/Map/Visualization/Patrolling/LineOfSightVertexVisualizationMode.cs
Assets/Scripts/Map/Visualization/Patrolling/LineOfSightVertexVisualizationMode.cs.meta
Assets/Scripts/Simulation/PatrollingSimulation.cs
Assets/Scripts/Statistics/PatrollingVisualizer.cs
Assets/Scripts/Trackers/PatrollingTracker.cs
Assets/Scripts/UI/CameraController.cs
Assets/Scripts/UI/Patrolling/LineOfSightVertices.cs
Assets/Scripts/UI/Patrolling/LineOfSightVertices.cs.meta
Assets/Scripts/UI/Patrolling/VertexVisualizer.cs
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs
Assets/Scripts/UI/SimulationInfoUIControllers/SimulationInfoUIControllerBase.cs
Assets/Scripts/Utilities/LineOfSightUtilities.cs
Assets/Scripts/Utilities/LineOfSightUtilities.cs.meta
Assets/Scripts/Utilities/MapUtilities.cs
Assets/Scripts/Utilities/MapUtilities.cs.meta

Line of side for all vertices and selected vertex

Line of side for all vertices and selected vertex

---

Assets/Scripts/Trackers/PatrollingTracker.cs
Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs

The slider returns a value in [0;1], so I multiply by the set max size, which is shown on the pictures. It's big enough right?

Robot highlighting slider functionality

---

Assets/Scripts/ExplorationAlgorithm/Voronoi/VoronoiExplorationAlgorithm.cs

It was broken in an optimization pass.

Fix the voronoi algorithm

---

Assets/Scripts/FaultInjections/DestroyRobots/DestroyRobotsAtSpecificTickFaultInjection.cs

This is what is used in the slides. It would be nice if the code is the same.

Cleanup fault injection

---

Assets/Scenes/RandomReactive.unity
Assets/Scenes/RandomReactive.unity.meta
Assets/Scripts/ExperimentSimulations/RandomReactiveExperiment.cs
Assets/Scripts/PatrollingAlgorithms/RandomReactive.cs

Before it used unity's random number generator.
This thing does not take a seed so it would be non-deterministic. It has been replaced with System.Random which does take a seed.
Fixes #198

Make random reactive deterministic

---

Assets/Scripts/Map/MapPatrollingGen/PatrollingMapRectangleGen.cs
Assets/Scripts/Map/MapPatrollingGen/WatchmanRouteSolver.cs
Assets/Scripts/Map/PatrollingMap.cs
Assets/Scripts/UI/Patrolling/LineOfSightVertices.cs

This makes starting a simulation faster. and we'll be doing that a lot this semester.
Don't know if it should just be a hard-coded change or maybe specified in some configuration file or something like that?

Use the breakfastcolumn version of LOS

---

Hooks/install-hooks.bat
Hooks/install-hooks.sh
Hooks/pre-commit
README.md

Added a pre-commit hook which runs the formatting script on commit.

Pre-commit hooks which run the formatting script

---

Assets/Scripts/ExperimentSimulations/ConscientiousReactiveExperiment.cs

Fixed spawn positions, robots can now spawn on the entire map

---

Assets/Scripts/PatrollingAlgorithms/CognitiveCoordinated.cs

#177 
I figured a cache would be the easiest to implement.
Additionally, this doesn't cause a slow startup.

Add path cache for CC algorithm

---

Assets/Scripts/Algorithms/Exploration/HenrikAlgo/HenrikExplorationAlgorithm.cs

Update header in HenrikExplorationAlgo

---

Assets/Scripts/Statistics/PatrollingVisualizer.cs
Assets/Scripts/Statistics/Visualizer.cs
Assets/Scripts/Trackers/Tracker.cs
Assets/Scripts/Visualizers/IVisualizer.cs

Fixed map offset in visualizations mode

---

Assets/EditTests/Benchmarks/BitmapBenchmarks.cs
Assets/EditTests/Benchmarks/LineOfSightBenchmarks.cs
Assets/EditTests/ComputeVisibilityTest.cs
Assets/Scripts/Map/MapPatrollingGen/GreedyWaypointGenerator.cs
Assets/Scripts/UI/Patrolling/LineOfSightVertices.cs
Assets/Scripts/Utilities/Bitmap.cs
Assets/Scripts/Utilities/VisibilityJob.cs

Optimize los

---

Assets/Prefabs/MAEPS.prefab
Assets/Scripts/Map/CoarseGrainedMap.cs
Assets/Scripts/Map/MapGen/BitMapGenerator.cs
Assets/Scripts/Map/MapGen/BuildingGenerator.cs
Assets/Scripts/Map/MapGen/CaveGenerator.cs
Assets/Scripts/Map/MapGen/MapGenerator.cs
Assets/Scripts/Map/MapGen/MeshGenerator.cs
Assets/Scripts/Map/MapGen/Room.cs
Assets/Scripts/Timing.meta
Assets/Scripts/Timing/TimeStart.cs
Assets/Scripts/Timing/TimeStart.cs.meta
Assets/Scripts/Utilities/Bitmap.cs
Assets/Scripts/Utilities/Files/SaveMapAsImage.cs

Bitmap is generally faster and uses a lot less memory.
Depends on #247

Use Bitmap more places instead of Bool[,]

---

Assets/Scripts/Map/MapPatrollingGen/WaypointConnection.cs
Assets/Scripts/Map/Partitioning/PartitioningGen.cs

(cherry picked from commit 9fadbcfcf1fa742086c6b02415d4faa71dfde1b9)

Fix mistake breaking everything by @S3JER

---

Assets/Scripts/Map/MapPatrollingGen/GreedyWaypointGenerator.cs
Assets/Scripts/Map/Partitioning/PartitioningGen.cs

https://en.wikipedia.org/wiki/Art_gallery_problem
NOT: https://en.wikipedia.org/wiki/Travelling_salesman_problem

It's watchman route not TSP

---

Assets/Scripts/Map/Partitioning/PartitioningGen.cs
Assets/Scripts/Utilities/MathUtilities.cs

Move methods to math util. Also cache calculation of average distance.

Refactor math methods to MathUtilities

---

Assets/Scripts/Map/Generators/Patrolling/Partitioning/AdapterToPartitionGenerator.cs
Assets/Scripts/Map/Generators/Patrolling/Partitioning/AdapterToPartitionGenerator.cs.meta
Assets/Scripts/Map/Generators/Patrolling/Partitioning/BasePartitionGenerator.cs
Assets/Scripts/Map/Generators/Patrolling/Partitioning/BasePartitionGenerator.cs.meta
Assets/Scripts/Map/Generators/Patrolling/Partitioning/PartitionInfo.cs
Assets/Scripts/Map/Generators/Patrolling/Partitioning/PartitionInfo.cs.meta
Assets/Scripts/Map/Generators/Patrolling/Partitioning/PartitioningGenerator.cs
Assets/Tests/EditModeTests/AdapterToPartitionGeneratorTest.cs
Assets/Tests/EditModeTests/AdapterToPartitionGeneratorTest.cs.meta

This PR allows us to use the existing partition generator and gives an Dictionary<int, PartitionInfo> where the key is the robot id and the PartitionInfo contains the information of the partition (a list of vertex ids) for the given robot id.
In a future PR, the PartitionInfo will contain information of the meeting point and time :)

Adapter to the existing partition generator

---

Assets/Scenes/HMPPatrolling.unity
Assets/Scenes/HMPPatrolling.unity.meta
Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs
Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs.meta
Assets/Scripts/Algorithms/Patrolling/Components/StartupComponent.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithm.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithm.cs.meta
Assets/Scripts/Algorithms/Patrolling/IPatrollingAlgorithm.cs
Assets/Scripts/Algorithms/Patrolling/PatrollingAlgorithm.cs
Assets/Scripts/Experiments/Patrolling/HMPPatrollingExperiment.cs
Assets/Scripts/Experiments/Patrolling/HMPPatrollingExperiment.cs.meta
Assets/Scripts/Map/SlamMap.cs
Assets/Tests/PlayModeTests/Algorithms/Patrolling/Components/StartupTests.cs

Stores the initial partition in the virtual stigmergy by utilising the `PartitionComponent`
Also, the initial setup to our algorithm is made in this PR
Depends on #317

Partition Component + Setup to HMP patrolling algorithm

---

Assets/Scripts/Map/Generators/Patrolling/Partitioning/PartitioningGenerator.cs
Assets/Scripts/Map/Generators/Patrolling/Waypoints/Connectors/ReverseNearestNeighborWaypointConnector.cs
Assets/Scripts/Map/Vertex.cs

This is step 1 in making connectVerticies actually only connect verticies :)

Extract partition id from connect verticies

---

Assets/Scripts/Experiments/Patrolling/HMPPatrollingExperiment.cs
Assets/Scripts/Map/Generators/Patrolling/Waypoints/Connectors/AllConnectedWaypointConnector.cs

Now the HMP use the all waypoint connected option

HMP use all waypoint connected option

---

Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs
Assets/Scripts/Algorithms/Patrolling/Components/VirtualStigmergyComponent.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithm.cs
Assets/Tests/PlayModeTests/Algorithms/Patrolling/Components/VirtualStigmergyTests.cs

Now you can have any type as the key.

Virtual Stigmergy: Make the key type generic

---

Assets/Scripts/Robot/Robot2DController.cs
Assets/Scripts/Robot/TravelEstimator.cs
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestStraightPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestStraightPath.cs.meta
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestTurnsPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestTurnsPath.cs.meta

Now the estimation function overestimates.
This PR also checks that the estimation overestimates.

Ensure that the estimation function overestimates

---

Assets/Scripts/Algorithms/Patrolling/Components/IComponent.cs
Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs
Assets/Scripts/Algorithms/Patrolling/Components/StartupComponent.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithm.cs
Assets/Scripts/Algorithms/Patrolling/PatrollingAlgorithm.cs
Assets/Tests/PlayModeTests/Algorithms/Patrolling/Components/StartupTests.cs

This allows us to encapsulate functionality into components that make use of other components.
Also add a Marker type to StartupComponent.

Allow components to make other components

---

Assets/Scripts/Simulation/Exploration/ExplorationSimulation.cs
Assets/Scripts/Simulation/Patrolling/PatrollingSimulation.cs
Assets/Scripts/Simulation/SimulationBase.cs
Assets/Scripts/Simulation/SimulationManager.cs
Assets/Scripts/Simulation/SimulationScenario.cs
Assets/Scripts/Utilities/TimeUtilities.cs
Assets/Scripts/Utilities/TimeUtilities.cs.meta

Add experiment folder

---

Assets/Scenes/Main.unity
Assets/Scenes/Main.unity.meta
Assets/Scripts/CommandlineExperimentSpawner.cs
Assets/Scripts/CommandlineExperimentSpawner.cs.meta
ProjectSettings/EditorBuildSettings.asset
run-scripts/run-headless.sh
run-scripts/run.sh

Choose the experiment with the `--experiment <experiment name>` commandline option.

Choose experiment with commandline option

---

Assets/Scripts/ExplorationScenarioGenerator.cs
Assets/Scripts/Simulation/Exploration/ExplorationSimulationScenario.cs
Assets/Scripts/Simulation/ISimulation.cs
Assets/Scripts/Simulation/Patrolling/PatrollingSimulation.cs
Assets/Scripts/Simulation/Patrolling/PatrollingSimulationScenario.cs
Assets/Scripts/Simulation/SimulationBase.cs
Assets/Scripts/Simulation/SimulationManager.cs
Assets/Scripts/Simulation/SimulationScenario.cs
Assets/Tests/PlayModeTests/Algorithms/Exploration/MinotaurDoorwayTest.cs
Assets/Tests/PlayModeTests/CommunicationTest.cs
Assets/Tests/PlayModeTests/EstimateTickTest/EstimateTestStraightPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/EstimateTestTurnsPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestStraightPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestTurnsPath.cs
Assets/Tests/PlayModeTests/ExplorationCsvDataWriterTest.cs
Assets/Tests/PlayModeTests/FaultInjections/DestroyRobots/CheckMultipleScenarioCanBeRunWithoutFailFaultInjectionTest.cs
Assets/Tests/PlayModeTests/FaultInjections/DestroyRobots/Random/DestroyRobotsRandomEveryTickFaultInjectionTest.cs
Assets/Tests/PlayModeTests/FaultInjections/DestroyRobots/Random/DestroyRobotsRandomZeroProbabilityFaultInjectionTest.cs
Assets/Tests/PlayModeTests/FaultInjections/DestroyRobots/SpecificTick/DestroyRobotsAtTicksFaultInjectionTest.cs
Assets/Tests/PlayModeTests/MaterialCommunicationTest.cs
Assets/Tests/PlayModeTests/Robot2DControllerTest.cs

This aborts the scenario after 100000 ticks (about 3 simulated hours). The value is configurable.
Implements #396

Abort after 100000 ticks

---

Assets/Scripts/Algorithms/Patrolling/Components/VirtualStigmergyComponent.cs

This allows for constinuous broadcasting of values in the stigmergy.

Add SendAll method to VirtualStigmergy

---

Assets/Scripts/Experiments/Patrolling/CognitiveCoordinatedExperiment.cs
Assets/Scripts/Experiments/Patrolling/CognitiveCoordinatedVirtualStigmergyExperiment.cs
Assets/Scripts/Experiments/Patrolling/ConscientiousReactiveExperiment.cs
Assets/Scripts/Experiments/Patrolling/ConscientiousReactiveExperimentWithFaultInjection.cs
Assets/Scripts/Experiments/Patrolling/HeuristicConscientiousReactiveExperiment.cs
Assets/Scripts/Experiments/Patrolling/PartitionedConscientiousReactiveExperiment.cs
Assets/Scripts/Experiments/Patrolling/RandomReactiveExperiment.cs
Assets/Scripts/Experiments/Patrolling/SingleCycleChristofidesExperiment.cs
Assets/Scripts/Experiments/Patrolling/SingleCycleTSPExperiment.cs

Just to reduce the amount of code, and make the experiments more readable.

Use the spawn apart method

---

Assets/Tests/PlayModeTests/EstimateTickTest/EstimateTestStraightPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/EstimateTestTurnsPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestStraightPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/OverEstimateTestTurnsPath.cs
Assets/Tests/PlayModeTests/EstimateTickTest/TestToTargetTileAlgorithm.cs

Fix flakey tests

---

Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithm.cs
Assets/Scripts/Experiments/Patrolling/HMPPatrollingExperiment.cs
Assets/Tests/PlayModeTests/Algorithms/Patrolling/HMPPatrollingAlgorithmTests/HmpPatrollingOwnPartitionTest.cs
Assets/Tests/PlayModeTests/Algorithms/Patrolling/HMPPatrollingAlgorithmTests/MeetAtTheMeetingPointTest.cs

Disable the component that checks if it still able to reach the next vertex and meeting if in collision recovery mode

Disable the component that checks if it still able to reach the next vertex and meeting if in collision recovery mode

---

Assets/Scripts/Map/PathFinding/IPathFinder.cs
Assets/Scripts/Map/PathFinding/MyAStar.cs
Assets/Scripts/Map/PathFinding/NewAStar.cs
Assets/Scripts/Map/PathFinding/NewAStar.cs.meta
Assets/Scripts/Map/PatrollingMap.cs
Assets/packages.config

This implementation works directly on the maps instead of having to construct a graph before hand.
This is about 10x as fast and uses almost no memory.

Use custom astar implementation

---

Assets/Scripts/Map/PathFinding/NewAStar.cs

AStar: Penalize direction changes

---

.github/workflows/main.yml
Packages/manifest.json
Packages/packages-lock.json

I ran this 5 times with no CI failure.
Takes ~100 seconds of the CI.

CI: Enable burst

---

.github/workflows/main.yml
Packages/manifest.json
Packages/packages-lock.json

This reverts commit cf347042f6a821997b0c01b63ff6611781b67745.

Revert "CI: Enable burst"

---

run-scripts/run-headless.sh
run-scripts/run.sh

We now add a timestamp and instance id on the output. The output is also added to the file output.log.
You can filter out instances by grepping the log file.

run-scripts: Add timestamp and instance id and log to output.log

---

Guide_VirtualMachine.md

Add a simple example command line of running an experiment in headless mode

Guide: Add an example of how to run an experiment in headless mode

---

Assets/Scripts/Algorithms/Patrolling/Group-cs-25-ds-10-16/GlobalRedistributionWithCRAlgo.cs
Assets/Scripts/Algorithms/Patrolling/PatrollingAlgorithm.cs
Assets/Scripts/Robot/Robot2DController.cs
Assets/Scripts/Statistics/Trackers/PatrollingTracker.cs

Added a check such that the tracking of visiting all waypoints in a partition never will have waypoints from another partition

Global Redistribution Fix

---

Assets/Scripts/Algorithms/Patrolling/HeuristicConscientiousReactive/HeuristicConscientiousReactiveLogic.cs

Fix hcr crashing

---

ProjectSettings/ProjectSettings.asset

This strips shaders and fonts, disables the audio subsystem, removes callbacks for rendering, input, etc.

Enable dedicated server optimizations

---

Assets/Scripts/Map/Generators/Patrolling/Waypoints/Generators/GreedyMostVisibilityWaypointGenerator.cs

Waypoint generator: Penalize waypoints close to a wall

---

.github/workflows/main.yml
Assets/Scripts/Robot/Robot2DController.cs
Assets/Scripts/Simulation/SimulationBase.cs
Assets/Scripts/Simulation/SimulationManager.cs
Assets/Scripts/Statistics/Trackers/Tracker.cs
Assets/Scripts/UI/CameraController.cs
Assets/Scripts/UI/DebuggingVisualizer.cs
Assets/Scripts/UI/SimulationInfoUIControllers/SimulationInfoUIControllerBase.cs
Assets/Scripts/UI/SimulationSpeedController.cs
Assets/Scripts/UI/Tooltip.cs
Assets/Scripts/UI/Visualizers/Exploration/ExplorationVisualizer.cs
Assets/Scripts/UI/Visualizers/IVisualizer.cs
Assets/Scripts/UI/Visualizers/Patrolling/PatrollingVisualizer.cs
Assets/Scripts/UI/Visualizers/Visualizer.cs
ProjectSettings/ProjectSettings.asset

Add a define `MAEPS_GUI` which is only defined when not compiling for the dedicated server.
Use this to conditionally compile functions that are used for gui stuff.

Dedicated server build: Compile out gui stuff

---

Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs

All robots don't necessarily spawn together anymore.

Partition Component: Put all info from startup component into the stigmergy

---

.gitignore
MAEPS-Data-Processor/AlgorithmSplitter/AlgorithmSplitter.csproj
MAEPS-Data-Processor/AlgorithmSplitter/ArgumentParser.cs
MAEPS-Data-Processor/AlgorithmSplitter/DataPreProcessor.cs
MAEPS-Data-Processor/AlgorithmSplitter/Grouping.cs
MAEPS-Data-Processor/AlgorithmSplitter/Program.cs
MAEPS-Data-Processor/AlgorithmSplitter/SummaryCreator.cs
MAEPS-Data-Processor/MAEPS-Data-Processor.sln

This splits the experiments such that it first groups by a value given in the scenario name for instance "size-", and then groups by the algorithm name inside the group bys

Data processor

---

MAEPS-Data-Processor/AlgorithmSplitter/Boxplots/BoxPlotCreator.cs
MAEPS-Data-Processor/AlgorithmSplitter/Boxplots/BoxplotCalculator.cs
MAEPS-Data-Processor/AlgorithmSplitter/Grouping.cs
MAEPS-Data-Processor/AlgorithmSplitter/Program.cs
MAEPS-Data-Processor/AlgorithmSplitter/SummaryCreator.cs

Able to make a boxplot of the data.
Here is an example output:

Creating boxplot of the experiment data

---

Assets/Scripts/Simulation/SimulationManager.cs

Log when starting a scenario

---

Assets/Scripts/Simulation/SimulationManager.cs

Ensure we prepend experiment folder name

---

Assets/Scripts/FaultInjections/DestroyRobots/DestroyRobotBaseFaultInjection.cs
Assets/Scripts/FaultInjections/IFaultInjection.cs
Assets/Scripts/Simulation/ISimulation.cs
Assets/Scripts/Simulation/SimulationBase.cs
Assets/Scripts/UI/SimulationInfoUIControllers/SimulationInfoUIControllerBase.cs
Assets/UI/ExplorationUserInterface.uxml
Assets/UI/PatrollingUserInterface.uxml

This PR adds the option to destroy a robot by clicking on the robot, and then, click on the Destroy button in the right panel

Destroy robot UI button

---

Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/ImmediateTakeover/HMPPatrollingAlgorithm.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/NoFaultTolerance/HMPPatrollingAlgorithm.cs

Used a wrong value for global meeting cycle

Fix global meeting cycle

---

Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultTolerance/HMPPatrollingAlgorithm.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultTolerance/MeetingComponent.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultTolerance/MeetingPoints/MeetingPoint.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultTolerance/PartitionComponent.cs
Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultTolerance/PartitionInfo.cs
Assets/Scripts/Algorithms/Patrolling/HeuristicConscientiousReactive/HeuristicConscientiousReactiveLogic.cs

Instead of meeting at an interval decide when the next next meeting takes place when attending a meeting.

Meet at agreed upon times

---

Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeToRobotCountRatioExperiment.cs

Gave wrong robot count to algorithms

---

Assets/Scripts/Experiments/Exploration/AvariceExploratoryExperiment.cs
Assets/Scripts/Experiments/Patrolling/CommonMapCRExperiment.cs
Assets/Scripts/Experiments/Patrolling/GroupA/GroupAExperimentHelpers.cs
Assets/Scripts/Experiments/Patrolling/ScenarioUtill.cs
Assets/Scripts/ExplorationScenarioGenerator.cs
Assets/Scripts/Map/Generators/BitmapConfig.cs
Assets/Scripts/Map/Generators/BitmapConfig.cs.meta
Assets/Scripts/Map/Generators/BuildingMapConfig.cs
Assets/Scripts/Map/Generators/CaveMapConfig.cs
Assets/Scripts/Map/Generators/IMapConfig.cs
Assets/Scripts/Map/Generators/IMapConfig.cs.meta
Assets/Scripts/Map/Generators/MapSpawner.cs
Assets/Tests/PlayModeTests/Algorithms/Exploration/MinotaurDoorwayTest.cs
Assets/Tests/PlayModeTests/Algorithms/Patrolling/Components/StartupTests.cs
Assets/Tests/PlayModeTests/Algorithms/Patrolling/Components/VirtualStigmergyTests.cs
Assets/Tests/PlayModeTests/CommunicationTest.cs
Assets/Tests/PlayModeTests/MaterialCommunicationTest.cs

I was annoyed at how the GroupAExperimentHelpers looked, due to map configs not having any common type.

Combine map configs

---

Assets/Scripts/Map/Generators/MeshGenerator.cs
Assets/Scripts/UI/Visualizers/Patrolling/VertexVisualizer.cs
Assets/Scripts/UI/Visualizers/Visualizer.cs
Assets/Scripts/Utilities/VertexColorMeshVisualizer.cs

This should be it for the mesh memory leaks.

Fix the rest of mesh memory leaks

---

Assets/Scripts/Experiments/Patrolling/GroupA/GroupAExperimentHelpers.cs

In both cavemap and buildmap scenario, there was wrote BuildingMap in the statisticsFileName.

Fix map name in statisticsFileName

---

Assets/Scripts/Map/RayTracingMap.cs
Assets/Scripts/Utilities/Line2D.cs

Remove the need for the move away from 90 degrees hacks.
It is slower, in the exploration play mode tests (except for one), but the robot does take a slightly different path which might explain most of the performance loss. Anyway, I think correctness trumps a little performance in this case. It would be possible to optimize this in the future if necessary.

Fix Line2D intersection

---

Assets/Scenes/Patrolling/GroupAExperimentScenes/GroupAMapSizestartupTimeExperiment.unity
Assets/Scenes/Patrolling/GroupAExperimentScenes/GroupAMapSizestartupTimeExperiment.unity.meta
Assets/Scripts/Experiments/Patrolling/GroupA/GroupAExperimentHelpers.cs
Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeStartupTimeExperiment.cs
Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeStartupTimeExperiment.cs.meta
Assets/Scripts/Simulation/SimulationManager.cs

Michele asked for this.
Also I've added such that the scenario generator can take the amount of cycles as parameter.
Use some grep on output.log:

Startup time experiment

---

Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeExperiment.cs
Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeToRobotCountRatioExperiment.cs
Assets/Scripts/Experiments/Patrolling/GroupA/GroupAParameters.cs
Assets/Scripts/Experiments/Patrolling/GroupA/GroupARobotCountExperiment.cs

Use all algorithm plus increase the seeds

Use AllAlgortihms for RatioMapSizeRobotCount

---

Assets/Scripts/Map/PathFinding/NewAStar.cs
Assets/Scripts/Map/PatrollingMap.cs
Assets/Scripts/Utilities/MapUtilities.cs

For patrolling map use the bitmap version of the astar algo. Also calculate both directions at once, by reversing.
Multi-thread MapUtilities.CalculateDistanceMatrix.

Even more optimizations

---

MAEPS-Data-Processor/MAEPS.Data.Processor/Preprocessors/Grouping.cs

It did not group the folders correctly but is fixed now

Fix ratio plot

---

Assets/Scripts/Experiments/Patrolling/GroupA/GroupAParameters.cs

We don't use material communication

---

Assets/Scripts/Simulation/Simulator.cs

Allows the user to specify a regex to filter which scenarios to run. Only scenarios matching the filter will run.
Specify the filter with `--filter "^RandomTakeover.*-size-100"` To only run takeover algorithm with map size of 100.

Filter scenarios by regex

---

Assets/Scripts/Utilities/Bitmap.cs
Assets/Tests/EditModeTests/Benchmarks/BitmapBenchmarks.cs

Double the performance of the bitmap enumerator by using some bit manipulation tricks.

Optimize bitmap enumerator and any
