Assets/Scripts/Map/Visualization/Patrolling/CoverageHeatMapVisualizationMode.cs, Assets/Scripts/Map/Visualization/Patrolling/CoverageHeatMapVisualizationMode.cs.meta, Assets/Scripts/Map/Visualization/Patrolling/PatrollingHeatMapVisualizationMode.cs, Assets/Scripts/Map/Visualization/Patrolling/PatrollingHeatMapVisualizationMode.cs.meta, Assets/Scripts/Trackers/PatrollingTracker.cs, Assets/Scripts/UI/SimulationInfoUIControllers/ExplorationInfoUIController.cs, Assets/Scripts/UI/SimulationInfoUIControllers/PatrollingInfoUIController.cs, Assets/Scripts/UI/SimulationInfoUIControllers/SimulationInfoUIControllerBase.cs
This PR allows
- To view the patrolling and coverage heat map.
- See which button has been selected in the patrolling UI.
- Change the name of the buttons since it was wrong typed before.
There is one bug: when selecting from Waypoint heat map to coverage heat map the Waypoint heat map is still viewed but not updated. Therefore when switching away from Waypoint heat map, the color of the waypoints should be standard color.
=> 3. Heatmap patrolling

Assets/Scripts/Statistics/PatrollingVisualizer.cs, Assets/Scripts/Trackers/PatrollingTracker.cs, Assets/Scripts/Trackers/Tracker.cs
- Resets the Patrolling UI after change mode.
- When the robot reaches a vertex, and the visualisation mode is "target waypoint", it resets the target vertex to default color
=> Resetting Patrolling UI after change mode

Assets/Scripts/CustomScriptsAssembly.asmdef, Assets/Scripts/Map/RayTracingMap.cs, Assets/Scripts/Map/SlamMap.cs, Assets/Scripts/Utilities/Functional.cs
Instead of using a list we use a stack allocated array. This is much faster as no allocations are needed as Vector2 and int are both "structs" aka stack allocated things.
=> Optimize raytracing

Assets/Scripts/ExplorationAlgorithm/Voronoi/VoronoiExplorationAlgorithm.cs, Assets/Scripts/Map/SlamMap.cs, Assets/Scripts/Map/VisibleTilesCoarseMap.cs, Assets/Scripts/Robot/ISlamAlgorithm.cs, ProjectSettings/Packages/com.unity.probuilder/Settings.json
Before it was a dictionary that was constantly recreated causing memory allocations.
Now it is a fixed-size multi-dimensional array.
This completely removes it from the profiler.
=> Optimize Visible Tiles

Assets/Scripts/Simulation/ExplorationSimulation.cs, Assets/Scripts/Simulation/PatrollingSimulation.cs, Assets/Scripts/Statistics/Communication.meta, Assets/Scripts/Statistics/Communication/CommunicationCsvDataWriter.cs, Assets/Scripts/Statistics/Communication/CommunicationCsvDataWriter.cs.meta, Assets/Scripts/Statistics/Communication/CommunicationSnapShot.cs, Assets/Scripts/Statistics/Communication/CommunicationSnapShot.cs.meta, Assets/Scripts/Statistics/Exploration/ExplorationCsvDataWriter.cs, Assets/Scripts/Statistics/Exploration/ExplorationSnapShot.cs, Assets/Scripts/Statistics/Patrolling.meta, Assets/Scripts/Statistics/Patrolling/PatrollingCsvDataWriter.cs, Assets/Scripts/Statistics/Patrolling/PatrollingCsvDataWriter.cs.meta, Assets/Scripts/Statistics/Patrolling/PatrollingSnapShot.cs, Assets/Scripts/Statistics/Patrolling/PatrollingSnapShot.cs.meta, Assets/Scripts/Statistics/Patrolling/WaypointSnapShot.cs, Assets/Scripts/Statistics/Patrolling/WaypointSnapShot.cs.meta, Assets/Scripts/Statistics/Writer/CsvDataWriter.cs, Assets/Scripts/Trackers/PatrollingTracker.cs, Assets/Scripts/Trackers/Tracker.cs
Logs the patrolling raw data to a CSV files.
It make a folder, that contains a CSV file called `patrolling.csv` and the a CSV file for each waypoints.
The `patrolling.csv` contains: Tick, Graph Idleness,  Current Worst Idleness, Distance Traveled, CompletedCycles, Agents Interconnected, Biggest Cluster %
Each waypoint files contains: Tick, Idleness, Number of visit.
Agents Interconnected, Biggest Cluster % is logged in both patrolling and exploration, and therefore `PatrollingSnapShot` and `ExplorationSnapShot` inherit from the `CommunicationSnapShot`, and a CsvDataWriter is implemented for `CommunicationSnapShot` that is used for both patrolling and exploration
=> Patrolling data to CSV

Assets/Scripts/Algorithms/IPatrollingAlgorithm.cs, Assets/Scripts/Map/MapPatrollingGen/PatrollingMapRectangleGen.cs, Assets/Scripts/Map/MapPatrollingGen/PatrollingWaypointGenerator.cs, Assets/Scripts/Map/PatrollingMap.cs, Assets/Scripts/Map/RobotSpawners/PatrollingRobotSpawner.cs, Assets/Scripts/Map/Vertex.cs, Assets/Scripts/Map/Visualization/Patrolling/PatrollingTargetWaypointVisualizationMode.cs, Assets/Scripts/PatrollingAlgorithms/ConscientiousReactiveAlgorithm.cs, Assets/Scripts/PatrollingAlgorithms/PatrollingAlgorithm.cs, Assets/Scripts/PatrollingAlgorithms/RandomReactive.cs, Assets/Scripts/Statistics/PatrollingVisualizer.cs, Assets/Scripts/Trackers/PatrollingTracker.cs, Assets/Scripts/Trackers/VertexDetails.cs, Assets/Scripts/Utilities/ICloneable.cs, Assets/Scripts/Utilities/ICloneable.cs.meta
Before when we cloned a vertex we kept all neighbors as the original references to the original vertices. This was broken as after the robot visited the first vertex it would go on to the global vertices and thus share knowledge with other robots.
Now we clone a whole PatrollingMap. This makes it so that we can clone all vertices in the map, changing the references to the neighbors to the cloned vertices.
This uncovered some bugs that depended on that the algorithms would visit the target vertex (which was form the global vertices) for visualizing.
Also as a bonus made patrolling map generator twice as fast and reduce code duplication in patrolling algorithms.
=> Fix vertex cloning

Assets/Scripts/ExperimentSimulations/ConscientiousReactiveExperiment.cs, Assets/Scripts/Map/CoarseGrainedMap.cs, Assets/Scripts/Map/PathFinding/AStar.cs, Assets/Scripts/Map/PathFinding/IPathFinder.cs, Assets/Scripts/Map/PatrollingMap.cs, Assets/Scripts/Map/VisibleTilesCoarseMap.cs, Assets/Scripts/PatrollingAlgorithms/PatrollingAlgorithm.cs, Assets/Scripts/Statistics/PatrollingVisualizer.cs
Before it would stop at every tile.
Now if there is a straight line it moves uninterrupted to the end of the line.
Patrolling visualizer now shows the pathsteps for the neighbors.
=> Patrolling: Use pathsteps to move instead of tiles

Assets/Scripts/Map/MapPatrollingGen/WatchmanRouteSolver.cs
Execution time for method:
` public static PatrollingMap MakePatrollingMap(SimulationMap<Tile> simulationMap)`
On my machine: before 6.7 sec, after 3.4 sec.
This would still be about 34 sec on Z's machine.
=> Watchman route parallelization

Assets/Scripts/Map/MapPatrollingGen/WatchmanRouteSolver.cs
Add short-circuit in foreach loop.
The method went from 1.5 sec to ~0.6 sec.
=> ComputeVertexCoordinates optimization

Assets/Scripts/PatrollingAlgorithms/PatrollingAlgorithm.cs
This fixes a weird bug where the robot would get stuck in a wall after some cycles.
Only on linux...
=> Fix: use different path when colliding

Assets/Scripts/Simulation/SimulationBase.cs
OnSimulationFinished is only called once, and therefore the bool can be removed
=> Remove bool _hasWrittenStatistics from simulationBase

Assets/EditTests/ComputeVisibilityTest.cs
This test case illustrates the difference between the original and optimized version.
The test case added:
Blue is starting point, red is not visible by any of them. Therefore making the 8th column not contain any visible tiles, causing the optimized version to stop prematurely. Green is therefore only visible by the original algorithm but not the optimized version. Currently, the original version is in use in the program.
=> Add a test for ComputeVisibilityOfPoint

Assets/PlayModeTests/PatrollingSimulatorBuildingMapTestTest.cs, Assets/PlayModeTests/PatrollingSimulatorBuildingMapTestTest.cs.meta, Assets/PlayModeTests/PatrollingSimulatorCaveMapTestTest.cs, Assets/PlayModeTests/PatrollingSimulatorCaveMapTestTest.cs.meta, Assets/PlayModeTests/StandardTestingConfiguration.cs
Both on building map and cave map
=> Add tests that run patrolling until completion

Assets/Scripts/Algorithms/IAlgorithm.cs, Assets/Scripts/Map/Visualization/Patrolling/PatrollingTargetWaypointVisualizationMode.cs
This allows for advanced algorithms that does not make use of the PatrollingAlgorithm base class.
=> target waypoint visualizer: Use IPatrollingAlgorithm instead

Assets/Scripts/Algorithms/IPatrollingAlgorithm.cs, Assets/Scripts/ExperimentSimulations/CognitiveCoordinatedExperiment.cs, Assets/Scripts/Map/RobotSpawners/PatrollingRobotSpawner.cs, Assets/Scripts/Map/Vertex.cs, Assets/Scripts/PatrollingAlgorithms/CognitiveCoordinated.cs, Assets/Scripts/PatrollingAlgorithms/ConscientiousReactiveAlgorithm.cs, Assets/Scripts/PatrollingAlgorithms/PatrollingAlgorithm.cs, Assets/Scripts/PatrollingAlgorithms/RandomReactive.cs, Assets/Scripts/UI/Patrolling/VertexVisualizer.cs
Use the global patrolling map, so the robots know about the real idleness of all vertices.
Create a coordinator to coordinate which vertices robots occupy to avoid going to the same vertex.
Clean up the code in many places, to make it nicer on the slides.
=> Fix Cognitive Coordinated

Assets/Scripts/PatrollingAlgorithms/PatrollingAlgorithm.cs
#153 
Now the robot actually reaches the vertex before marking it as visited, as can be seen by the heatmap.
Alternatively, add debug logging for the OnReachTargetVertex method.
=> Fixed prematurely marking vertex as visited

Assets/Scripts/ExperimentSimulations/AvariceExperiment.cs, Assets/Scripts/ExperimentSimulations/ExampleProgram.cs, Assets/Scripts/ExperimentSimulations/ExplorationExperimentBase.cs, Assets/Scripts/ExperimentSimulations/ExplorationTimeoutTest.cs, Assets/Scripts/ExperimentSimulations/HenrikExample.cs, Assets/Scripts/ExperimentSimulations/MinotaurExperiments.cs, Assets/Scripts/ExperimentSimulations/RandomReactiveExperiment.cs, Assets/Scripts/ExperimentSimulations/TnfExperiments.cs, Assets/Scripts/ExperimentSimulations/WallFollowerExperiment.cs, Assets/Scripts/Map/RobotSpawners/RobotSpawner.cs, Assets/Scripts/UI/RestartRemakeControllers/RestartRemakeController.cs
Now the robots are spawned at the same spot when restarting the simulation
The SpawnRobotsTogether is now using a random starting point if a suggestedStartingPoint is not given. Most experiments used a random starting point, but generated a random starting point at each restart. This has been removed at moved into the SpawnRobotsTogether method, such that is gives a random starting point using the incoming seed, and ensure to start at the same random starting point.
=> Fix non deterministic behaviour when restarting a simulation

Assets/Scripts/Algorithms/Patrolling/ConscientiousReactiveAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/RandomReactive.cs
I only added sources to the ones I'm sure of. I think we should do it for all of them. This way furture groups don't need to compare code to pseudocode to check which version of a patrolling algorithm we've implemented.
=> Add sources to the patrolling algorithms

Assets/Scripts/Statistics/Trackers/PatrollingTracker.cs
No vertex selected. Click the communication zone button. There is a debug log about how no vertex has been selected. But, the mesh render is enabled making it look like above, even when the UI says we are in "none" mode (which we are actually not). But, when clicking the none button, the mesh render is disabled, and everything is fine.
Even more fun happens when we select waypoint LOS mode. Then click none. Then click communication zone mode. The UI says we are in none mode, since we have not selected a waypoint. But the mesh render now displays as if we are in waypoint LOS mode:
=> Bugfix: Don't set mesh render if no vertex is selected

Assets/Scripts/UI/Visualizers/Patrolling/VisualizationModes/SelectedRobotCommunicationRangeVisualizationMode.cs
If the robot hasn't moved to a different tile, don't update the map wrt. communication range, since the communication range is tile based.
Now it is just a little laggy on 1x speed. Before it was completely unresponsive...
=> Refactor selected-robot-communication-visualizer

Assets/Scripts/Statistics/Trackers/PatrollingTracker.cs, Assets/Scripts/UI/Visualizers/Patrolling/CommunicationZoneVertices.cs, Assets/Scripts/UI/Visualizers/Patrolling/VisualizationModes/CommunicationZoneVisualizationMode.cs, Assets/Scripts/UI/Visualizers/Patrolling/VisualizationModes/SelectedRobotCommunicationRangeVisualizationMode.cs, Assets/Scripts/UI/Visualizers/Visualizer.cs, Assets/Tests/EditModeTests/CommunicationZoneVerticesTests.cs
The visualization mode was broken.
The ctor would set the map colors, but the map is reset in SetVisualizationMode()
I fixed this.
Also now it uses bitmaps for stuff instead of weird datatypes.
The bitmap => triangleIndecies convertion has been moved to the visualizer, since multiple visualization mode make this mapping.
=> Refactor visualizer for bitmaps

Assets/Scripts/Map/Generators/Patrolling/Partitioning/PartitioningGenerator.cs, Assets/Scripts/Map/Generators/Patrolling/Waypoints/Connectors/ReverseNearestNeighborWaypointConnector.cs, Assets/Scripts/Simulation/Patrolling/PatrollingSimulationScenario.cs
Remove the color islands debug functionality.
The color islands functionality was used to color partitions, which is convoluted.
It's much more simple now, also fewer parameters have to be supplied to the methods.
=> Refactor rnn waypoint connector

Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs, Assets/Scripts/Algorithms/Patrolling/Components/VirtualStigmergyComponent.cs, Assets/Tests/PlayModeTests/Algorithms/Patrolling/Components/VirtualStigmergyTests.cs
This changes some stuff as we cannot rely on being able to return null. Instead we do TryGet-style getters.
This is much cleaner tbh as we are now allowed to send null values.
=> Virtual Stigmergy: Allow value types in TValue

Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs
It seems like unity deletes Debug code when building in release mode. This fucked up as the TryGet function call was inside the Debug.Assert call. This is a unity bug. Work around it! Time to file a bug to unity? :)
=> Fix release build error

Assets/Scripts/Algorithms/Patrolling/Components/PartitionComponent.cs, Assets/Scripts/Algorithms/Patrolling/Components/VirtualStigmergyComponent.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithm.cs, Assets/Tests/PlayModeTests/Algorithms/Patrolling/Components/VirtualStigmergyTests.cs
This allows the user to have multiple virtual stigmergies that share the same key and value types.
Without this messages sent from one VirtualStigmergy<int, int> would be sent to another.
To have multiple VirtualStigmergy's with the same type in one class, create private marker classes inside the class.
For example:
```cs
private sealed class VertexMarker {}
private sealed class RobotMarker {}
VirtualStigmergy<int, int, VertexMarker> _vertexStigmergy;
VirtualStigmergy<int, int, RobotMarker> _robotStigmergy;
```
vertexStigmergy and robotStigmergy will not recieve each others messages as they are distinct types.
=> Virtual Stigmergy: Add marker type to differentiate stigmergies with same key,value types

Assets/Scripts/Algorithms/Patrolling/Components/VirtualStigmergyComponent.cs, Assets/Scripts/Map/Generators/Patrolling/Partitioning/MeetingPoints/MeetingPoint.cs, Assets/Scripts/Map/Generators/Patrolling/Partitioning/MeetingPoints/PartitionGeneratorWithMeetingPoint.cs, Assets/Scripts/Map/Generators/Patrolling/Partitioning/PartitionInfo.cs, Assets/Scripts/Utilities/PartitionsExtensions.cs
Clone the value when receiving it from a message. This stops reference types from leaking information.
This forces things to implement IClonable. However, if the class is immutable, it should just return this instead of cloning, to improve performance.
Depends on #355
=> Immutable value virtual stigmergy

Assets/Scripts/Experiments/Patrolling/HMPPatrollingExperiment.cs, Assets/Scripts/Map/Generators/Patrolling/Partitioning/MeetingPoints/PartitionGeneratorWithMeetingPoint.cs, Assets/Scripts/Map/Generators/Patrolling/Waypoints/Connectors/AllConnectedWaypointConnector.cs, Assets/Scripts/Map/Generators/Patrolling/Waypoints/Connectors/ReverseNearestNeighborWaypointConnector.cs, Assets/Scripts/Map/PatrollingMap.cs, Assets/Scripts/Utilities/PartitionsExtensions.cs, Assets/Tests/EditModeTests/MeetingPointsWithTimeTest.cs, Assets/Tests/EditModeTests/PartitionGeneratorWithMeetingPointTest.cs, Assets/Tests/EditModeTests/PartitionGeneratorWithMeetingPointTest.cs.meta, Assets/Tests/EditModeTests/Utilities/MapInterpreter/MapBuilder/PartitionSimulationMapBuilder.cs
Previously the meeting points were not correctly found. If two partitions are not sharing a common vertex, but they are neighbor meaning an edge between one of vertices in partition A and one of vertices in partition B, then a one of the vertices should be meeting point. However since all vertices are connected with all vertices, all partitions are neighbor to each other. That is not good, and are now fixed in this PR.
=> Finding sharing vertices between the neighbor partition instead of all partitions

Assets/Scripts/Simulation/Patrolling/PatrollingSimulation.cs
If there are 99 waypoints, there would be 99 statistics files. This would make it hard to find the config dump and the combined result file.
Multiple scenarios in one experiment:
=> Save waypoint statistics in subfolder

Assets/Scripts/Map/Generators/Patrolling/Partitioning/MeetingPoints/MeetingPointTimePartitionGenerator.cs, Assets/Tests/EditModeTests/MeetingPointsWithTimeTest.cs
After making the pseudocode, there is a mistake in the HMPAlgorithm.
The first meeting that is created with time information works correct. But then the rest created meetings' time are wrong.
For example the second created meeting is meet every 2 * globalIntervalMeetingTick, but it should just be globalIntervalMeetingTick.
For example the third created meeting is meet every 3 * globalIntervalMeetingTick, but it should just be globalIntervalMeetingTick.
=> Important fix to HMPAlgorithm

Assets/Scripts/Algorithms/Patrolling/Components/GoToNextVertexComponent.cs, Assets/Scripts/Map/PathFinding/MyAStar.cs, Assets/Scripts/Map/PatrollingMap.cs
This makes it less likely that robots collide with walls.
Add simple collision recovery in GoToNextVertexComponent. If the robot is colliding rotate and move the robot to the target. Collision recovery can still be delegated to another more advanced component, but this works well for wall collision recovery.
=> AStar: Penalize tiles close to walls

Assets/Scripts/Utilities/PatrollingVerticesExtension.cs
- Robots now correctly select the initial vertex
=> Robots always selected vertex 0 at simulation start

Assets/Scripts/Algorithms/Patrolling/Components/GoToNextVertexComponent.cs
This PR ensures that if AbortCurrentTask is called, then afterwards it moves to the vertex specified in the AbortCurrentTask. This mechanism was previously handled by another component, but may not be enabled in all cases. Therefore the check in GoToNextComponent on line 120, ensure that is goes to the vertex specified the aborting task.
=> Fix aborting task mechanism

Assets/Scripts/Map/PathFinding/MyAStar.cs, Assets/Scripts/Map/PathFinding/NewAStar.cs, Assets/Scripts/Map/PatrollingMap.cs
NewAStar: Add depend on broken behaviour
When the collision map is broken it says there is a wall where there isnt. To account for this if the goal is one tile into a wall, allow the robot to move into it.
NewAstar: Implement partial paths
A partial path just paths to the closest coordinate to the target if a direct path cannot be found due to unseen tiles.
=> NewAStar: Implement broken behaviour and partial paths

Assets/Scenes/GroupAExperimentScenes/GroupAMapSizetoRobotCountRatioExperiment.unity, Assets/Scenes/GroupAExperimentScenes/GroupAMapSizetoRobotCountRatioExperiment.unity.meta, Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeExperiment.cs, Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeToRobotCountRatioExperiment.cs, Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeToRobotCountRatioExperiment.cs.meta
- Experiment to find the optimal ratio of robot count / map size.
- Move mapsize to be the second outer-most foreach, such that the sequential distribution of scenarios on cloud instances has better chances of being of same mapsize, which give more cache-hits for the waypoint generation
=> Add experiment to find optimal ratio of robot count / map size

Assets/Scenes/DebugScenarioFailureExperiment.unity, Assets/Scenes/DebugScenarioFailureExperiment.unity.meta, Assets/Scripts/Experiments/Patrolling/DebugScenarioFailureExperiment.cs, Assets/Scripts/Experiments/Patrolling/DebugScenarioFailureExperiment.cs.meta, Assets/Scripts/Experiments/Patrolling/GroupA/GroupAExperimentHelpers.cs, Assets/Scripts/Experiments/Patrolling/GroupA/GroupAParameters.cs, Assets/Scripts/Simulation/Patrolling/PatrollingSimulation.cs, Assets/Scripts/Simulation/SimulationManager.cs, Assets/Scripts/Statistics/Writer/CsvDataWriter.cs, run-scripts/run-headless.sh, run-scripts/run.sh
#446 
This makes a file called failure.log with the names of all experiments that fail.
This outcomments CRPartitioning, since it's broken.
This removes the logging of the csv writer which logs for every waypoint csv file, which is spam.
This makes an experiment to check if the script runs successfully, which it does, I tested it.
=> Add scenario name to error log

Assets/Scripts/Statistics/CsvDataWriter.cs, ProjectSettings/ProjectSettings.asset
When calling Finish() I forgot to dispose the stream writer which probably held the file.
=> CsvDataWriter: Fix file is being used error

run-scripts/run-headless.sh, run-scripts/run.sh
This makes it easy to see which exceptions occurred, and when. Then the user can check that timestamp in output.log to see why.
=> Make an exceptions-log file

Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultTolerance/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultToleranceV2/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/ImmediateTakeover/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/NoFaultTolerance/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/RandomTakeover/HMPPatrollingAlgorithm.cs, Assets/Scripts/Map/Generators/BuildingGenerator.cs, Assets/Scripts/Map/Generators/CaveGenerator.cs, Assets/Scripts/Map/Generators/Patrolling/Partitioning/PartitioningGenerator.cs, Assets/Scripts/Map/Generators/Patrolling/Waypoints/Connectors/ReverseNearestNeighborWaypointConnector.cs, Assets/Scripts/Map/Generators/Patrolling/Waypoints/Generators/GreedyMostVisibilityWaypointGenerator.cs, Assets/Scripts/Map/Generators/Tile.cs, Assets/Scripts/Map/PatrollingMap.cs, Assets/Scripts/Map/SlamMap.cs, Assets/Scripts/Statistics/Cell.cs, Assets/Scripts/Statistics/Trackers/ExplorationTracker.cs, Assets/Scripts/Utilities/VisibilityJob.cs, Assets/Tests/EditModeTests/Benchmarks/LineOfSightBenchmarks.cs, Assets/Tests/EditModeTests/ComputeVisibilityTest.cs
Optimize Visibility calculations by only tracing to the border of the map. This is inaccurate though, but should be good enough for the things we use visibility calculations for. This is many times faster than the accurate version.
Multithread generating paths between vertices on patrolling map. This is especially noticable when using everyone connected to everyone and or on big maps.
Use a SortedSet in Greedy Most Visibility Waypoint Connector to avoid having to sort every iteration. (about 33% performance improvement).
Only calculate Distance Matrix once. This is extremely expensive and doing this multiple times was extremely slow.
Other small optimizations.
This takes about 30 seconds off the CI.
=> More optimizations

Assets/Scenes/Patrolling/HMPPartitionVariants/SingleMeetingPoint.unity, Assets/Scenes/Patrolling/HMPPartitionVariants/SingleMeetingPoint.unity.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/HMPPatrollingAlgorithm.cs.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/MeetingComponent.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/MeetingComponent.cs.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/MeetingPoints.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/MeetingPoints/MeetingPoint.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/MeetingPoints/MeetingPoint.cs.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/PartitionComponent.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/PartitionComponent.cs.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/PartitionInfo.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/PartitionInfo.cs.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/TrackInfos.meta, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/TrackInfos/ExchangeInfoAtMeetingTrackInfo.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/TrackInfos/ExchangeInfoAtMeetingTrackInfo.cs.meta, Assets/Scripts/Experiments/Patrolling/HMPPartitionVariants/HMPPatrollingSingleMeetingPointExperiment.cs, Assets/Scripts/Experiments/Patrolling/HMPPartitionVariants/HMPPatrollingSingleMeetingPointExperiment.cs.meta, Assets/Scripts/Map/PathFinding/NewAStar.cs, Assets/Tests/PlayModeTests/Algorithms/Patrolling/HMPPatrollingAlgorithmTests/AllHMPPatrollingAlgorithm.cs
Every partition has a single meeting point all connected to each other. Robots no longer need to negotiate next meeting point as it is cycle interval based.
Robots instantly take over a partition if another robot is missing.
=> Add HMP Single Meeting point variant

run-scripts/run-headless.sh, run-scripts/run.sh
Now you can run some instance on one computer and some on other computers
For instance, on one computer run instance 0 to including instance 127
`./run-headless.sh Patrolling.GroupAMapSizeToRobotCountRatioExperiment 256 0 127`
and, on another computer run instance 128 to including instance 255
`./run-headless.sh Patrolling.GroupAMapSizeToRobotCountRatioExperiment 256 128 255`
=> Specify the range of instance to run

Assets/Scripts/Experiments/Patrolling/DebugScenarioFailureExperiment.cs, Assets/Scripts/Experiments/Patrolling/GroupA/GroupAExperimentHelpers.cs, Assets/Scripts/Experiments/Patrolling/GroupA/GroupAMapSizeStartupTimeExperiment.cs
Instead of using cycles we now just run the scenario for 2000 * map width ticks and we can then make our conclusions based on worst and average idleness.
=> Stop after reaching 2000 * map width

Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/FaultTolerance/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/ImmediateTakeover/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/NoFaultTolerance/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/RandomTakeover/HMPPatrollingAlgorithm.cs, Assets/Scripts/Algorithms/Patrolling/HMPPatrollingAlgorithms/SingleMeetingPoint/HMPPatrollingAlgorithm.cs
We mistakingly did `D + D * Ceil(|V| / |M|)` instead of `D * Ceil(|V| / |M|)`
=> Fix Meeting Interval
